apiVersion: kinda.rocks/v1beta1
kind: DbBackup
metadata:
  name: mysql
spec:
  database: mysql
  image:
    registry: localhost
    repository: db-backup-cli
    tag: latest
  uploadCredentialsSecret: test-mysql
