apiVersion: kinda.rocks/v1beta1
kind: DbBackup
metadata:
  generateName: postgres-
spec:
  database: postgres
  debug: true
  image:
    registry: localhost
    repository: db-backup-cli
    tag: latest
  uploadCredentialsSecret: test
