{{- $root := . }}
{{- $nodeSelector := .Values.nodeSelector }}
{{- $exporter := .Values.exporter.postgres }}
{{- $fullName := include "db-instances.fullname" . }}
{{- if .Values.dbinstances }}
{{- range $name, $value := .Values.dbinstances }}
{{- if eq $value.engine "postgres" }}
{{- if $value.monitoring.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbinstance-{{ $name }}-pgexporter
spec:
  replicas: 1
  selector:
    matchLabels:
      db-instance: {{ $name }}
      {{- include "db-instances.selectorLabels" $ | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        {{- include "db-instances.labels" $ | nindent 8 }}
        db-instance: {{ $name }}
        {{- with $value.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - env:
        - name: DATA_SOURCE_URI
          value: {{ $value.monitoring.uri | default (printf "dbinstance-%s-svc:5432/postgres?sslmode=disable" $name) }}
        - name: DATA_SOURCE_PASS_FILE
          value: /run/secrets/db-secrets/{{ $value.monitoring.passwordKey | default "password" }}
        - name: DATA_SOURCE_USER_FILE
          value: /run/secrets/db-secrets/{{ $value.monitoring.usernameKey | default "user" }}
        image: {{ $exporter.image }}
        imagePullPolicy: Always
        name: exporter
        ports:
        - name: http
          containerPort: 9187
        volumeMounts:
        - mountPath: /run/secrets/db-secrets
          name: db-secrets
      nodeSelector:
        {{ toYaml $nodeSelector | nindent 8 }}
      volumes:
      - name: db-secrets
        secret:
          defaultMode: 420
  {{- if $value.adminUserSecret }}
          secretName: {{ $value.adminUserSecret }}
  {{- else }}
          secretName: {{ $name }}-admin-secret
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: dbinstance-{{ $name }}-pgexporter
  labels:
    db-instance: {{ $name }}
    {{- include "db-instances.labels" $ | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "db-instances.selectorLabels" $ | nindent 4 }}
    db-instance: {{ $name }}
{{- if $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- if ($value.serviceMonitor).enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: dbinstance-{{ $name }}-sm
  labels:
    db-instance: {{ $name }}
    {{- include "db-instances.labels" $ | nindent 4 }}
    {{- with $value.serviceMonitor.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $value.serviceMonitor.jobLabel }}
  jobLabel: {{ $value.serviceMonitor.jobLabel }}
  {{- end }}
  endpoints:
    - port: http
      {{- with $value.serviceMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with $value.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $value.serviceMonitor.metricRelabelings }}
      metricRelabelings:
      {{- if kindIs "string" . }}
        {{- tpl . $ | nindent 8 }}
      {{- else }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with $value.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      db-instance: {{ $name }}
{{- if $value.serviceMonitor.targetLabels }}
  targetLabels:
  {{- range $value.serviceMonitor.targetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- if $.Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
{{- if ($value.podMonitor).enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: dbinstance-{{ $name }}-pm
  labels:
    db-instance: {{ $name }}
    {{- include "db-instances.labels" $ | nindent 4 }}
    {{- with $value.podMonitor.selector }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if $value.podMonitor.jobLabel }}
  jobLabel: {{ $value.podMonitor.jobLabel }}
  {{- end }}
  podMetricsEndpoints:
    - port: http
      {{- with $value.podMonitor.interval }}
      interval: {{ . }}
      {{- end }}
      {{- with $value.podMonitor.scrapeTimeout }}
      scrapeTimeout: {{ . }}
      {{- end }}
      {{- with $value.podMonitor.metricRelabelings }}
      metricRelabelings:
      {{- if kindIs "string" . }}
        {{- tpl . $ | nindent 8 }}
      {{- else }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      {{- with $value.podMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace }}
  selector:
    matchLabels:
      db-instance: {{ $name }}
{{- if $value.podMonitor.podTargetLabels }}
  podTargetLabels:
  {{- range $value.podMonitor.podTargetLabels }}
    - {{ . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}