---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "db-instances.labels" . | nindent 4 }}
  name: {{ template "db-instances.fullname" . }}-pgexporter-query
data:
  queries.yaml: |
    {{- toYaml .Values.exporter.postgres.query | nindent 4 }}
