name: Helm workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  HELM_VERSION: v4.1.0
  HELMFILE_VERSION: v1.2.3
  PYTHON_VERSION: 3.14

jobs:
  long-test:
    needs: quick-tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s_version:
          - v1.35.0
          - v1.34.3
          - v1.33.7
          - v1.32.11
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v6

      - name: Set up Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: ${{ env.HELM_VERSION }}

      - uses: actions/setup-python@v6
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: Prepare a config for the kind cluster
        run: |
          cat > kind-config.yaml <<EOF
          # three node (two workers) cluster config
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
            - role: worker
            - role: worker
          EOF

      - name: Create kind cluster
        uses: helm/kind-action@v1.13.0
        with:
          node_image: kindest/node:${{ matrix.k8s_version }}
          config: ./kind-config.yaml

      - name: Deploy the helmfile (without db-operator)
        uses: helmfile/helmfile-action@v2.2.0
        with:
          helmfile-version: ${{ env.HELMFILE_VERSION }}
          helm-version: ${{ env.HELM_VERSION }}
          helmfile-auto-init: true
          helmfile-args: sync --wait -l purpose!=db-operator

      - name: Test the db-operator chart install
        run: |
          ct install --target-branch main --charts ./charts/db-operator
      # -- TODO: Enabled it again
      # -- Test of the older versions are not passing anymore, hence upgrade can't be tested
      # - name: Test the db-operator chart upgrade
      #  run: |
      #    ct install --target-branch main --charts ./charts/db-operator --upgrade

      - name: Deploy the helmfile (with db-operator this time)
        uses: helmfile/helmfile-action@v2.2.0
        with:
          helmfile-version: ${{ env.HELMFILE_VERSION }}
          helm-version: ${{ env.HELM_VERSION }}
          helmfile-args: sync --wait

      - name: Test posgres and mysql database integrations
        uses: helmfile/helmfile-action@v2.2.0
        with:
          helmfile-version: ${{ env.HELMFILE_VERSION }}
          helm-version: ${{ env.HELM_VERSION }}
          helmfile-args: test -l purpose=test

      - name: Test db-instances charts install
        run: |
          ct install --target-branch main --charts ./charts/db-instances

      - name: Test db-instances charts upgrade
        run: |
          ct install --target-branch main --charts ./charts/db-instances --upgrade

  release:
    runs-on: ubuntu-latest
    needs: long-test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Push Helm chart to OCI compatible registry (Github)
        run: |
          export BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          export SHA="+$(git rev-parse --short HEAD)"
          helm registry login ghcr.io \
            --username ${{ github.actor }} \
            --password ${{ github.token }}
          for chart in $(find charts -maxdepth 1 -mindepth 1 -type d); do
            if [ "${BRANCH}" != "main" ]; then
              yq e -i ".version += env(SHA)" "$chart/Chart.yaml"
            fi
            helm dep build $chart
            helm package $chart -d chart-packages;
          done
          charts=$(find chart-packages -maxdepth 1 -mindepth 1 -type f)
          REGISTRY=$(echo oci://ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]')
          for chart in $charts; do
            echo ${chart}
            echo "${REGISTRY}"
            helm push "${chart}" "${REGISTRY}"
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
