repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: jetstack
    url: https://charts.jetstack.io

charts:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    createNamespace: true
    needs: 
      - monitoring/prometheus-stack
    values:
      - installCRDs: true
  - name: postgres-instance
    installed: true
    namespace: postgres
    createNamespace: true
    chart: bitnami/postgresql
    needs: 
      - monitoring/prometheus-stack
    values:
      - global:
          postgresql:
            auth:
              postgresPassword: 123123!!
  - name: prometheus-stack
    namespace: monitoring
    createNamespace: true
    disableValidationOnInstall: true
    chart: prometheus-community/kube-prometheus-stack
    values:
      - prometheus:
          prometheusSpec:
            enableAdminAPI: true
            podMonitorNamespaceSelector:
              any: true
            podMonitorSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            ruleNamespaceSelector:
              any: true
            ruleSelector: {}
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector:
              any: true
            serviceMonitorSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false
  - name: db-operator
    namespace: db-operator
    createNamespace: true
    chart: ../../db-operator
    needs: 
      - cert-manager/cert-manager
