environments:
  default:
  instances:

---
repositories:
  - name: jetstack
    url: https://charts.jetstack.io
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: v1.16.1
    createNamespace: true
    values:
      - crds:
          enabled: true

  - name: postgres-instance
    namespace: databases
    chart: bitnami/postgresql
    version: 16.0.6
    values:
    - global: 
        postgresql:
          auth:
            postgresPassword: 123123!!

  - name: mysql-instance
    namespace: databases
    chart: bitnami/mysql
    version: 11.1.19
    values:
      - auth:
          rootPassword: 123123!!
          password: 123123!!
  
  - name: prometheus-stack
    namespace: monitoring
    version: 65.3.2
    createNamespace: true
    disableValidation: true
    disableOpenAPIValidation: true
    chart: prometheus-community/kube-prometheus-stack
    needs:
      - cert-manager/cert-manager
    values:
      - prometheus:
          prometheusSpec:
            enableAdminAPI: true
            podMonitorNamespaceSelector:
              any: true
            podMonitorSelector: {}
            podMonitorSelectorNilUsesHelmValues: false
            ruleNamespaceSelector:
              any: true
            ruleSelector: {}
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorNamespaceSelector:
              any: true
            serviceMonitorSelector: {}
            serviceMonitorSelectorNilUsesHelmValues: false

  - name: db-operator
    namespace: db-operator
    createNamespace: true
    installed: {{ eq .Environment.Name "instances" | toYaml }}
    chart: ./charts/db-operator
    needs:
      - monitoring/prometheus-stack
      - cert-manager/cert-manager
  
