apiVersion: kinda.rocks/v1beta1
kind: Database
metadata:
  name: mysql
spec:
  backup:
    enable: true
    cron: '*/5 * * * *'
    bucket: backups
    envFromSecret: s3-creds
  deletionProtected: false
  instance: mariadb
  secretName: mysql-creds
  cleanup: true
