---
apiVersion: v2
type: application
name: db-operator
version: 3.14.0
description: This operator lets you manage databases in a Kubernetes native way, even if they are not deployed to Kubernetes
# All supported k8s versions are in the test:
# https://github.com/db-operator/charts/blob/main/.github/workflows/integration-test.yaml
kubeVersion: ">= 1.32-prerelease"
appVersion: "f63b54145843dbb25601ce4e65e81ac73146fcb6"
home: https://github.com/db-operator
maintainers:
  - name: Nikolai Rodionov
    email: allanger@posteo.com
    url: https://badhouseplants.net
sources:
  - https://github.com/db-operator/db-operator
keywords:
  - database
  - mysql
  - postgres
