apiVersion: kinda.rocks/v1beta1
kind: DbRestore
metadata:
  name: postgres
spec:
  database: postgres
  image:
    registry: localhost
    repository: db-backup-cli
    tag: latest
  uploadCredentialsSecret: test
  cleanup: true
  backupPath: working-namespace/postgres
