---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "db-operator.controller.name" . }}-config
  labels:
    {{- include "db-operator.controller.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- .Values.controller.config | toYaml | nindent  4 }}
